server:
  port: 80
spring:
  application:
    name: consumer-80
eureka:
  client: #客户端进行eureka注册配置
    service-url:    #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://zcc:zcc@eureka-7002.com:7002/eureka,http://zcc:zcc@eureka-7001.com:7001/eureka,http://zcc:zcc@eureka-7003.com:7003/eureka
    register-with-eu·reka: false